# Generated by Django 6.0.2 on 2026-02-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
